package views;

import javax.swing.JComboBox;
import models.ClienteDAO;
import models.ConexionMysql;
import models.ProductoDAO;
import models.VentaDAO;

/**
 *
 * @author Chico
 */
public class Consultar extends javax.swing.JPanel {

    private MainWindow consultar;
    private ConexionMysql con;
    
    private String combo_seleccion;
    
    /**
     * Creates new form Consultar
     */
    public Consultar(MainWindow mainWindow, ConexionMysql con) {
        initComponents();
        this.consultar = mainWindow;
        this.con = con;
        mostrarContenido(this.cbox_tablas.getSelectedItem().toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_mostrar_todo = new javax.swing.JButton();
        cbox_tablas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbox_campo = new javax.swing.JComboBox<>();
        btn_mostrar = new javax.swing.JButton();
        textField_filtro_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btn_respaldar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(882, 665));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(1441, 652));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));

        jPanel2.setMinimumSize(new java.awt.Dimension(750, 571));
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 571));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Consultar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        btn_mostrar_todo.setText("Mostrar todo");
        btn_mostrar_todo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mostrar_todoMouseClicked(evt);
            }
        });

        cbox_tablas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Productos", "Ventas", "Clientes" }));
        cbox_tablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_tablasActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar por:");

        cbox_campo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Producto", "ID Almacen", "Nombre", "Tamaño", "Precio", "Costo", "Fecha", "Stock" }));
        cbox_campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_campoActionPerformed(evt);
            }
        });

        btn_mostrar.setText("Mostrar");
        btn_mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mostrarMouseClicked(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Producto", "ID Almacen", "Nombre", "Tamaño", "Precio de venta", "Costo a la empresa", "Fecha de llegada", "Cantidad de stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setFocusable(false);
        tabla.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tabla);

        btn_respaldar.setText("Respaldar datos");
        btn_respaldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_respaldarActionPerformed(evt);
            }
        });

        jButton2.setText("Ayuda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbox_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField_filtro_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbox_tablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_mostrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_mostrar_todo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(btn_respaldar))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mostrar_todo)
                    .addComponent(cbox_tablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbox_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mostrar)
                    .addComponent(textField_filtro_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_respaldar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)))
        );

        btn_consultar.setText("Consultar");

        btn_agregar.setText("Agregar");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btn_consultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_eliminar)
                .addGap(18, 18, 18)
                .addComponent(btn_salir)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        jScrollPane4.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mostrar_todoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrar_todoMouseClicked
        mostrarContenido(this.cbox_tablas.getSelectedItem().toString());
    }//GEN-LAST:event_btn_mostrar_todoMouseClicked

    private void btn_mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrarMouseClicked
        consultaFiltro(this.cbox_campo.getSelectedItem().toString());
    }//GEN-LAST:event_btn_mostrarMouseClicked

    private void cbox_tablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_tablasActionPerformed
        comboOpciones(this.cbox_tablas.getSelectedItem().toString());
    }//GEN-LAST:event_cbox_tablasActionPerformed

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        consultar.setNewContent(new Agregar(consultar,con));
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
        consultar.setNewContent(new Modificar(consultar,con));
    }//GEN-LAST:event_btn_modificarMouseClicked

    private void btn_respaldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_respaldarActionPerformed
        con.exportarBaseDeDatos();
    }//GEN-LAST:event_btn_respaldarActionPerformed

    private void cbox_campoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_campoActionPerformed
        
    }//GEN-LAST:event_cbox_campoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        con.cerrarConexion();
        consultar.setNewContent(new Login(consultar));
        consultar.revalidate();
        consultar.repaint();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        consultar.setNewContent(new Eliminar(consultar,con));
        consultar.revalidate();
        consultar.repaint();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void mostrarContenido(String tabla){
        switch (tabla) {
            case "Productos":
                ProductoDAO.consultarTodov2(this.tabla);
                break;

            case "Ventas":
                VentaDAO.consultarTodov2(this.tabla);
                break;

            case "Clientes":
                ClienteDAO.ConsultarTodo(this.tabla);
                break;
        }
    }

    private void consultaFiltro(String filtro){
        if(this.cbox_tablas.getSelectedItem().toString().equals("Productos")){
            switch (filtro) {
                case "ID Producto":
                    ProductoDAO.consultaFiltro(this.tabla,"id_producto", this.textField_filtro_buscar.getText());
                    break;

                case "ID Almacen":
                    ProductoDAO.consultaFiltro(this.tabla,"id_almacen", this.textField_filtro_buscar.getText());
                    break;

                case "Nombre":
                    ProductoDAO.consultaFiltro(this.tabla,"nombre", this.textField_filtro_buscar.getText());
                    break;

                case "Tamaño":
                    ProductoDAO.consultaFiltro(this.tabla,"id_tamano", this.textField_filtro_buscar.getText());
                    break;

                case "Precio":
                    ProductoDAO.consultaFiltro(this.tabla,"precio_venta", this.textField_filtro_buscar.getText());
                    break;

                case "Costo":
                    ProductoDAO.consultaFiltro(this.tabla,"costo_empresa", this.textField_filtro_buscar.getText());
                    break;

                case "Fecha":
                    ProductoDAO.consultaFiltro(this.tabla,"fecha_llegada", this.textField_filtro_buscar.getText());
                    break;

                case "Stock":
                    ProductoDAO.consultaFiltro(this.tabla,"cantidad_inventario", this.textField_filtro_buscar.getText());
                    break;
                    
                case "Tipo producto":
                    ProductoDAO.consultaFiltro(this.tabla,"id_tipo_producto", this.textField_filtro_buscar.getText());
                    break;
            }
        }

        if(this.cbox_tablas.getSelectedItem().toString().equals("Ventas")){
            switch (filtro) {
                case "ID Venta":
                    VentaDAO.consultarFiltro(this.tabla, "v", "id_venta", this.textField_filtro_buscar.getText());
                    break;

                case "ID Cliente":
                    VentaDAO.consultarFiltro(this.tabla, "v","id_cliente", this.textField_filtro_buscar.getText());
                    break;
                    
                case "Nombre Cliente":
                    VentaDAO.consultarFiltro(this.tabla, "c","nombre", this.textField_filtro_buscar.getText());
                    break;
                    
                case "Domicilio":
                    VentaDAO.consultarFiltro(this.tabla, "c","domicilio", this.textField_filtro_buscar.getText());
                    break;
                    
                case "Telefono":
                    VentaDAO.consultarFiltro(this.tabla, "c","telefono", this.textField_filtro_buscar.getText());
                    break;
                 
                case "Producto Vendido":
                    VentaDAO.consultarFiltro(this.tabla, "p","nombre", this.textField_filtro_buscar.getText());
                    break;
                    
                case "Tipo Producto":
                    VentaDAO.consultarFiltro(this.tabla, "p","id_tipo_producto", this.textField_filtro_buscar.getText());
                    break;

                case "Precio":
                    VentaDAO.consultarFiltro(this.tabla, "p","precio_venta", this.textField_filtro_buscar.getText());
                    break;

                case "Monto Pagado":
                    VentaDAO.consultarFiltro(this.tabla, "v","pago_inicial", this.textField_filtro_buscar.getText());
                    break;

                case "Deuda Pendiente":
                    VentaDAO.consultarFiltro(this.tabla, "v","deuda_pendiente", this.textField_filtro_buscar.getText());
                    break;
                    
                case "Fecha de Venta":
                    VentaDAO.consultarFiltro(this.tabla, "v","fecha", this.textField_filtro_buscar.getText());
                    break;
            }
        }
        
        if(this.cbox_tablas.getSelectedItem().toString().equals("Clientes")){
            switch (filtro) {
                case "ID cliente":
                    ClienteDAO.ConsultarFiltro(tabla, "id_cliente", this.textField_filtro_buscar.getText());
                    break;

                case "Nombre":
                    ClienteDAO.ConsultarFiltro(tabla, "nombre", this.textField_filtro_buscar.getText());
                    break;

                case "Domicilio":
                    ClienteDAO.ConsultarFiltro(tabla, "domicilio", this.textField_filtro_buscar.getText());
                    break;

                case "Telefono":
                    ClienteDAO.ConsultarFiltro(tabla, "telefono", this.textField_filtro_buscar.getText());
                    break;

                case "Deuda pendiente":
                    ClienteDAO.ConsultarFiltro(tabla, "deuda_pendiente", this.textField_filtro_buscar.getText());
                    break;

                case "Crédito disponible":
                    ClienteDAO.ConsultarFiltro(tabla, "credito_disponible", this.textField_filtro_buscar.getText());
                    break;
            }
        }
        
    }
    
    private void comboOpciones(String seleccion){
        if (seleccion == "Productos") {
            this.cbox_campo.removeAllItems();
            this.cbox_campo.addItem("ID Producto");
            this.cbox_campo.addItem("ID Almacen");
            this.cbox_campo.addItem("Nombre");
            this.cbox_campo.addItem("Tamaño");
            this.cbox_campo.addItem("Precio");
            this.cbox_campo.addItem("Costo");
            this.cbox_campo.addItem("Fecha");
            this.cbox_campo.addItem("Stock");
        }
        if (seleccion == "Ventas") {
            this.cbox_campo.removeAllItems();
            this.cbox_campo.addItem("ID Venta");
            this.cbox_campo.addItem("ID Cliente");
            this.cbox_campo.addItem("Nombre Cliente");
            this.cbox_campo.addItem("Domicilio");
            this.cbox_campo.addItem("Telefono");
            this.cbox_campo.addItem("Producto Vendido");
            this.cbox_campo.addItem("Tipo Producto");
            this.cbox_campo.addItem("Precio");
            this.cbox_campo.addItem("Monto Pagado");
            this.cbox_campo.addItem("Deuda Pendiente");
            this.cbox_campo.addItem("Fecha de Venta");
        }
        if (seleccion == "Clientes") {
            this.cbox_campo.removeAllItems();
            this.cbox_campo.addItem("ID cliente");
            this.cbox_campo.addItem("Nombre");
            this.cbox_campo.addItem("Domicilio");
            this.cbox_campo.addItem("Telefono");
            this.cbox_campo.addItem("Deuda pendiente");
            this.cbox_campo.addItem("Crédito disponible");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_mostrar;
    public javax.swing.JButton btn_mostrar_todo;
    private javax.swing.JButton btn_respaldar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cbox_campo;
    private javax.swing.JComboBox<String> cbox_tablas;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable tabla;
    private javax.swing.JTextField textField_filtro_buscar;
    // End of variables declaration//GEN-END:variables
}
