package views;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Cliente;
import models.ClienteDAO;
import models.ConexionMysql;
import models.Producto;
import models.ProductoDAO;
import models.Venta;
import models.VentaDAO;

/**
 *
 * @author Chico
 */
public class Eliminar extends javax.swing.JPanel {

    private MainWindow eliminar;
    private ConexionMysql con;

    private String combo_seleccion;

    /**
     * Creates new form Consultar
     */
    public Eliminar(MainWindow eliminar, ConexionMysql con) {
        initComponents();
        this.eliminar = eliminar;
        this.con = con;

        this.panel_modificarVenta.setVisible(false);
        this.panel_modificarVenta.setEnabled(false);
        this.panel_modificarCliente.setVisible(false);
        this.panel_modificarCliente.setEnabled(false);
        mostrarContenido(this.cbox_tablas.getSelectedItem().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_mostrar_todo = new javax.swing.JButton();
        cbox_tablas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbox_campo = new javax.swing.JComboBox<>();
        btn_mostrar = new javax.swing.JButton();
        textField_filtro_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_modificar = new javax.swing.JTable();
        panel_modificarProducto = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_eliminarProducto = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        textField_productoIdProductoModificar = new javax.swing.JTextField();
        panel_modificarVenta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_eliminarVenta = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        textField_ventaIdVentaModificar = new javax.swing.JTextField();
        panel_modificarCliente = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btn_eliminarCliente = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        textField_clienteIdClienteModificar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(854, 652));

        jPanel2.setMinimumSize(new java.awt.Dimension(750, 571));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Eliminar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        btn_mostrar_todo.setText("Mostrar todo");
        btn_mostrar_todo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mostrar_todoMouseClicked(evt);
            }
        });

        cbox_tablas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Productos", "Ventas", "Clientes" }));
        cbox_tablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_tablasActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar por:");

        cbox_campo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Producto", "ID Almacen", "Nombre", "Tamaño", "Precio", "Costo", "Fecha", "Stock" }));

        btn_mostrar.setText("Mostrar");
        btn_mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mostrarMouseClicked(evt);
            }
        });

        tabla_modificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Producto", "Nombre producto", "Tipo producto", "Tamaño", "Almacen", "Precio de venta", "Costo a empresa", "Fehca de llegada", "Cantidad de inventario", "Porcentaje de ganancia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_modificarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_modificar);

        panel_modificarProducto.setEnabled(false);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Eliminar Producto");

        btn_eliminarProducto.setText("Eliminar");
        btn_eliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarProductoActionPerformed(evt);
            }
        });

        jLabel28.setText("ID Producto");

        textField_productoIdProductoModificar.setText("Ejemplo: \"1\"");

        javax.swing.GroupLayout panel_modificarProductoLayout = new javax.swing.GroupLayout(panel_modificarProducto);
        panel_modificarProducto.setLayout(panel_modificarProductoLayout);
        panel_modificarProductoLayout.setHorizontalGroup(
            panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modificarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_modificarProductoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_modificarProductoLayout.createSequentialGroup()
                        .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_modificarProductoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_eliminarProducto))
                            .addGroup(panel_modificarProductoLayout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField_productoIdProductoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90))))
        );
        panel_modificarProductoLayout.setVerticalGroup(
            panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modificarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(textField_productoIdProductoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_eliminarProducto)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Eliminar Venta");

        btn_eliminarVenta.setText("Eliminar");
        btn_eliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarVentaActionPerformed(evt);
            }
        });

        jLabel29.setText("ID Venta");

        textField_ventaIdVentaModificar.setText("Ejemplo: \"2\"");

        javax.swing.GroupLayout panel_modificarVentaLayout = new javax.swing.GroupLayout(panel_modificarVenta);
        panel_modificarVenta.setLayout(panel_modificarVentaLayout);
        panel_modificarVentaLayout.setHorizontalGroup(
            panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modificarVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panel_modificarVentaLayout.createSequentialGroup()
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField_ventaIdVentaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_modificarVentaLayout.createSequentialGroup()
                            .addGap(216, 216, 216)
                            .addComponent(btn_eliminarVenta))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        panel_modificarVentaLayout.setVerticalGroup(
            panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modificarVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(textField_ventaIdVentaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_eliminarVenta)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Eliminar Cliente");

        btn_eliminarCliente.setText("Eliminar");
        btn_eliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarClienteActionPerformed(evt);
            }
        });

        jLabel30.setText("ID Cliente");

        textField_clienteIdClienteModificar.setText("Ejemplo: \"Pedro Jesus\"");

        javax.swing.GroupLayout panel_modificarClienteLayout = new javax.swing.GroupLayout(panel_modificarCliente);
        panel_modificarCliente.setLayout(panel_modificarClienteLayout);
        panel_modificarClienteLayout.setHorizontalGroup(
            panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modificarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panel_modificarClienteLayout.createSequentialGroup()
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField_clienteIdClienteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_modificarClienteLayout.createSequentialGroup()
                            .addGap(216, 216, 216)
                            .addComponent(btn_eliminarCliente))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        panel_modificarClienteLayout.setVerticalGroup(
            panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modificarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(textField_clienteIdClienteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_eliminarCliente)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        jButton2.setText("Ayuda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbox_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_filtro_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbox_tablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_mostrar_todo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_modificarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_modificarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_modificarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mostrar_todo)
                    .addComponent(cbox_tablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbox_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mostrar)
                    .addComponent(textField_filtro_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(panel_modificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(panel_modificarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel_modificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(100, Short.MAX_VALUE))))))
        );

        btn_consultar.setText("Consultar");
        btn_consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultarMouseClicked(evt);
            }
        });

        btn_agregar.setText("Agregar");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btn_consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_eliminar)
                        .addGap(19, 19, 19)
                        .addComponent(btn_salir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mostrar_todoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrar_todoMouseClicked
        mostrarContenido(this.cbox_tablas.getSelectedItem().toString());
    }//GEN-LAST:event_btn_mostrar_todoMouseClicked

    private void btn_mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrarMouseClicked
        consultaFiltro(this.cbox_campo.getSelectedItem().toString());
    }//GEN-LAST:event_btn_mostrarMouseClicked

    private void cbox_tablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_tablasActionPerformed
        comboOpciones(this.cbox_tablas.getSelectedItem().toString());
        mostrarContenido(this.cbox_tablas.getSelectedItem().toString());
    }//GEN-LAST:event_cbox_tablasActionPerformed

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        eliminar.setNewContent(new Agregar(eliminar, con));
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void btn_consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarMouseClicked
        eliminar.setNewContent(new Consultar(eliminar, con));
    }//GEN-LAST:event_btn_consultarMouseClicked

    private void btn_eliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarProductoActionPerformed
        try {
            int id_producto = Integer.parseInt(this.textField_productoIdProductoModificar.getText());
            
            if (ProductoDAO.eliminarProducto(id_producto)) {
                JOptionPane.showMessageDialog(null, "Producto eliminado.");
            }
            mostrarContenido(this.cbox_tablas.getSelectedItem().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btn_eliminarProductoActionPerformed

    private void tabla_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_modificarMouseClicked
        try{
            tomarDatosTabla(this.cbox_tablas.getSelectedItem().toString());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_tabla_modificarMouseClicked

    private void btn_eliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarVentaActionPerformed
        try{
            int id_venta = Integer.parseInt(this.textField_ventaIdVentaModificar.getText());
            if (VentaDAO.eliminarVenta(id_venta)) {
                JOptionPane.showMessageDialog(null, "Venta eliminado.");
            }
            mostrarContenido(this.cbox_tablas.getSelectedItem().toString());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btn_eliminarVentaActionPerformed

    private void btn_eliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarClienteActionPerformed
        try{
            int id_cliente = Integer.parseInt(this.textField_clienteIdClienteModificar.getText());
            if (ClienteDAO.eliminarCliente(id_cliente)) {
                JOptionPane.showMessageDialog(null, "Cliente eliminado.");
            }
            mostrarContenido(this.cbox_tablas.getSelectedItem().toString());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btn_eliminarClienteActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        con.cerrarConexion();
        eliminar.setContentPane(new Login(eliminar));
        eliminar.revalidate();
        eliminar.repaint();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        eliminar.setContentPane(new Modificar(eliminar, con));
        eliminar.revalidate();
        eliminar.repaint();
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void mostrarContenido(String tabla){
        switch (tabla) {
            case "Productos":
                ProductoDAO.consultarTodov2(tabla_modificar);
                break;

            case "Ventas":
                VentaDAO.consultarTodov2(tabla_modificar);
                break;

            case "Clientes":
                ClienteDAO.ConsultarTodo(tabla_modificar);
                break;
        }
    }
    
    private void consultaFiltro(String filtro) {
        if (this.cbox_tablas.getSelectedItem().toString().equals("Productos")) {
            switch (filtro) {
                case "ID Producto":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "id_producto", this.textField_filtro_buscar.getText());
                    break;

                case "ID Almacen":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "id_almacen", this.textField_filtro_buscar.getText());
                    break;

                case "Nombre":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "nombre", this.textField_filtro_buscar.getText());
                    break;

                case "Tamaño":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "id_tamano", this.textField_filtro_buscar.getText());
                    break;

                case "Precio":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "precio_venta", this.textField_filtro_buscar.getText());
                    break;

                case "Costo":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "costo_empresa", this.textField_filtro_buscar.getText());
                    break;

                case "Fecha":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "fecha_llegada", this.textField_filtro_buscar.getText());
                    break;

                case "Stock":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "cantidad_inventario", this.textField_filtro_buscar.getText());
                    break;

                case "Tipo producto":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "id_tipo_producto", this.textField_filtro_buscar.getText());
                    break;
            }
        }

        if (this.cbox_tablas.getSelectedItem().toString().equals("Ventas")) {
            switch (filtro) {
                case "ID Venta":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "v", "id_venta", this.textField_filtro_buscar.getText());
                    break;

                case "ID Cliente":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "v", "id_cliente", this.textField_filtro_buscar.getText());
                    break;

                case "Nombre Cliente":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "c", "nombre", this.textField_filtro_buscar.getText());
                    break;

                case "Domicilio":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "c", "domicilio", this.textField_filtro_buscar.getText());
                    break;

                case "Telefono":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "c", "telefono", this.textField_filtro_buscar.getText());
                    break;

                case "Producto Vendido":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "p", "nombre", this.textField_filtro_buscar.getText());
                    break;

                case "Tipo Producto":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "p", "id_tipo_producto", this.textField_filtro_buscar.getText());
                    break;

                case "Precio":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "p", "precio_venta", this.textField_filtro_buscar.getText());
                    break;

                case "Monto Pagado":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "v", "pago_inicial", this.textField_filtro_buscar.getText());
                    break;

                case "Deuda Pendiente":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "v", "deuda_pendiente", this.textField_filtro_buscar.getText());
                    break;

                case "Fecha de Venta":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "v", "fecha", this.textField_filtro_buscar.getText());
                    break;
            }
        }

        if (this.cbox_tablas.getSelectedItem().toString().equals("Clientes")) {
            switch (filtro) {
                case "ID cliente":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "id_cliente", this.textField_filtro_buscar.getText());
                    break;

                case "Nombre":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "nombre", this.textField_filtro_buscar.getText());
                    break;

                case "Primer apellido":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "apellido1", this.textField_filtro_buscar.getText());
                    break;

                case "Segundo apellido":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "apellido2", this.textField_filtro_buscar.getText());
                    break;

                case "Deuda pendiente":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "deuda_pendiente", this.textField_filtro_buscar.getText());
                    break;

                case "Crédito disponible":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "credito_disponible", this.textField_filtro_buscar.getText());
                    break;

                case "Calle":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "calle", this.textField_filtro_buscar.getText());
                    break;

                case "Número casa":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "numero_casa", this.textField_filtro_buscar.getText());
                    break;

                case "Colonia":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "colonia", this.textField_filtro_buscar.getText());
                    break;

                case "Telefono":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "telefono", this.textField_filtro_buscar.getText());
                    break;
            }
        }
    }

    private void comboOpciones(String seleccion) {
        if (seleccion == "Productos") {
            this.cbox_campo.removeAllItems();
            this.cbox_campo.addItem("ID Producto");
            this.cbox_campo.addItem("ID Almacen");
            this.cbox_campo.addItem("Nombre");
            this.cbox_campo.addItem("Tamaño");
            this.cbox_campo.addItem("Precio");
            this.cbox_campo.addItem("Costo");
            this.cbox_campo.addItem("Fecha");
            this.cbox_campo.addItem("Stock");

            this.panel_modificarProducto.setVisible(true);
            this.panel_modificarProducto.setEnabled(true);
            this.panel_modificarVenta.setVisible(false);
            this.panel_modificarVenta.setEnabled(false);
            this.panel_modificarCliente.setVisible(false);
            this.panel_modificarCliente.setEnabled(false);
        }
        if (seleccion == "Ventas") {
            this.cbox_campo.removeAllItems();
            this.cbox_campo.addItem("ID Venta");
            this.cbox_campo.addItem("ID Cliente");
            this.cbox_campo.addItem("Nombre Cliente");
            this.cbox_campo.addItem("Domicilio");
            this.cbox_campo.addItem("Telefono");
            this.cbox_campo.addItem("Producto Vendido");
            this.cbox_campo.addItem("Tipo Producto");
            this.cbox_campo.addItem("Precio");
            this.cbox_campo.addItem("Monto Pagado");
            this.cbox_campo.addItem("Deuda Pendiente");
            this.cbox_campo.addItem("Fecha de Venta");

            this.panel_modificarProducto.setVisible(false);
            this.panel_modificarProducto.setEnabled(false);
            this.panel_modificarVenta.setVisible(true);
            this.panel_modificarVenta.setEnabled(true);
            this.panel_modificarCliente.setVisible(false);
            this.panel_modificarCliente.setEnabled(false);
        }
        if (seleccion == "Clientes") {
            this.cbox_campo.removeAllItems();
            this.cbox_campo.addItem("ID cliente");
            this.cbox_campo.addItem("Nombre");
            this.cbox_campo.addItem("Primer apellido");
            this.cbox_campo.addItem("Segundo apellido");
            this.cbox_campo.addItem("Deuda pendiente");
            this.cbox_campo.addItem("Crédito disponible");
            this.cbox_campo.addItem("Calle");
            this.cbox_campo.addItem("Número casa");
            this.cbox_campo.addItem("Colonia");
            this.cbox_campo.addItem("Telefono");

            this.panel_modificarProducto.setVisible(false);
            this.panel_modificarProducto.setEnabled(false);
            this.panel_modificarVenta.setVisible(false);
            this.panel_modificarVenta.setEnabled(false);
            this.panel_modificarCliente.setVisible(true);
            this.panel_modificarCliente.setEnabled(true);
        }
    }

    private int convertirAlmacen(String almacen) {
        switch (almacen) {
            case "ALFA":
                return 1;

            case "BETA":
                return 1;
        }

        return -1;
    }

    private int convertirTamaño(String tamanio) {
        switch (tamanio) {
            case "Chico":
                return 1;

            case "Mediano":
                return 2;

            case "Grande":
                return 3;

            case "Muy grande":
                return 4;
        }

        return -1;
    }

    private int convertirTipoProducto(String tipo) {
        switch (tipo) {
            case "Muebles":
                return 1;

            case "Electrodomésticos":
                return 2;
        }

        return -1;
    }

    private void tomarDatosTabla(String tabla){
        int row = this.tabla_modificar.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) this.tabla_modificar.getModel();

        switch (tabla) {
            case "Productos":
                row = this.tabla_modificar.getSelectedRow();
                model =(DefaultTableModel) this.tabla_modificar.getModel(); 
                
                this.textField_productoIdProductoModificar.setText(model.getValueAt(row, 0).toString());
                break;

            case "Ventas":
                row = this.tabla_modificar.getSelectedRow();
                model =(DefaultTableModel) this.tabla_modificar.getModel(); 
                
                this.textField_ventaIdVentaModificar.setText(model.getValueAt(row, 0).toString());
                break;

            case "Clientes":
                row = this.tabla_modificar.getSelectedRow();
                model =(DefaultTableModel) this.tabla_modificar.getModel(); 
                
                this.textField_clienteIdClienteModificar.setText(model.getValueAt(row, 0).toString());
                break;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_eliminarCliente;
    private javax.swing.JButton btn_eliminarProducto;
    private javax.swing.JButton btn_eliminarVenta;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_mostrar;
    public javax.swing.JButton btn_mostrar_todo;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cbox_campo;
    private javax.swing.JComboBox<String> cbox_tablas;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_modificarCliente;
    private javax.swing.JPanel panel_modificarProducto;
    private javax.swing.JPanel panel_modificarVenta;
    public javax.swing.JTable tabla_modificar;
    private javax.swing.JTextField textField_clienteIdClienteModificar;
    private javax.swing.JTextField textField_filtro_buscar;
    private javax.swing.JTextField textField_productoIdProductoModificar;
    private javax.swing.JTextField textField_ventaIdVentaModificar;
    // End of variables declaration//GEN-END:variables
}
