package views;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import models.Cliente;
import models.ClienteDAO;
import models.ConexionMysql;
import models.Producto;
import models.ProductoDAO;
import models.Venta;
import models.VentaDAO;

/**
 *
 * @author Chico
 */
public class Modificar extends javax.swing.JPanel {

    private MainWindow modificar;
    private ConexionMysql con;

    private String combo_seleccion;

    /**
     * Creates new form Consultar
     */
    public Modificar(MainWindow mainWindow, ConexionMysql con) {
        initComponents();
        this.modificar = mainWindow;
        this.con = con;

        this.panel_modificarVenta.setVisible(false);
        this.panel_modificarVenta.setEnabled(false);
        this.panel_modificarCliente.setVisible(false);
        this.panel_modificarCliente.setEnabled(false);
        mostrarContenido(this.cbox_tablas.getSelectedItem().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_mostrar_todo = new javax.swing.JButton();
        cbox_tablas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbox_campo = new javax.swing.JComboBox<>();
        btn_mostrar = new javax.swing.JButton();
        textField_filtro_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_modificar = new javax.swing.JTable();
        panel_modificarProducto = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textField_productoCantidadModificar = new javax.swing.JTextField();
        textField_productoFechaModificar = new javax.swing.JTextField();
        textField_productoCostoEmpresaModificar = new javax.swing.JTextField();
        textField_productoPrecioVentaModificar = new javax.swing.JTextField();
        textField_productoNombreModificar = new javax.swing.JTextField();
        combo_productoTipoProductoModificar = new javax.swing.JComboBox<>();
        combo_productoAlmacenModificar = new javax.swing.JComboBox<>();
        combo_productoTamañoModificar = new javax.swing.JComboBox<>();
        btn_actualizarProducto = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        textField_productoIdProductoModificar = new javax.swing.JTextField();
        panel_modificarVenta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        textField_VentaCantidadModificar = new javax.swing.JTextField();
        textField_VentaIdProductoModificar = new javax.swing.JTextField();
        textField_VentaIdClienteModificar = new javax.swing.JTextField();
        textField_VentaMontoModificar = new javax.swing.JTextField();
        textField_VentaFechaModificar = new javax.swing.JTextField();
        btn_actualizarVenta = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        textField_ventaIdVentaModificar = new javax.swing.JTextField();
        panel_modificarCliente = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        textField_clienteCreditoModificar = new javax.swing.JTextField();
        textField_clienteDeudaModificar = new javax.swing.JTextField();
        textField_clienteSegundoApellidoModificar = new javax.swing.JTextField();
        textField_clientePrimerApellidoModificar = new javax.swing.JTextField();
        textField_clienteNombreModificar = new javax.swing.JTextField();
        textField_clienteCalleModificar = new javax.swing.JTextField();
        textField_clienteNumCasaModificar = new javax.swing.JTextField();
        textField_clienteColoniaModificar = new javax.swing.JTextField();
        textField_clienteTelefonoModificar = new javax.swing.JTextField();
        btn_actualizarCliente = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        textField_clienteIdClienteModificar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(854, 652));

        jPanel2.setMinimumSize(new java.awt.Dimension(750, 571));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Modificar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        btn_mostrar_todo.setText("Mostrar todo");
        btn_mostrar_todo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mostrar_todoMouseClicked(evt);
            }
        });

        cbox_tablas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Productos", "Ventas", "Clientes" }));
        cbox_tablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_tablasActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar por:");

        cbox_campo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Producto", "ID Almacen", "Nombre", "Tamaño", "Precio", "Costo", "Fecha", "Stock" }));

        btn_mostrar.setText("Mostrar");
        btn_mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mostrarMouseClicked(evt);
            }
        });

        tabla_modificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Producto", "Nombre producto", "Tipo producto", "Tamaño", "Almacen", "Precio de venta", "Costo a empresa", "Fehca de llegada", "Cantidad de inventario", "Porcentaje de ganancia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_modificarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_modificar);

        panel_modificarProducto.setEnabled(false);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Modificar Producto");

        jLabel5.setText("Nombre producto");

        jLabel6.setText("Tipo producto");

        jLabel7.setText("Tamaño");

        jLabel8.setText("Almacen");

        jLabel9.setText("Precio de venta");

        jLabel10.setText("Costo a empresa");

        jLabel11.setText("Fecha de llegada");

        jLabel12.setText("Cantidad en inventario");

        textField_productoCantidadModificar.setText("Ejemplo: \"25\"");

        textField_productoFechaModificar.setText("Ejemplo: \"2024-11-05\"");

        textField_productoCostoEmpresaModificar.setText("Ejemplo: \"5000\"");

        textField_productoPrecioVentaModificar.setText("Ejemplo: \"15000\"");

        textField_productoNombreModificar.setText("Ejemplo: \"Lavadora Whirlpool\"");

        combo_productoTipoProductoModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muebles", "Electrodomésticos" }));

        combo_productoAlmacenModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALFA", "BETA" }));

        combo_productoTamañoModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chico", "Mediano", "Grande", "Muy grande" }));

        btn_actualizarProducto.setText("Actualizar");
        btn_actualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarProductoActionPerformed(evt);
            }
        });

        jLabel28.setText("ID Producto");

        textField_productoIdProductoModificar.setText("Ejemplo: \"1\"");

        javax.swing.GroupLayout panel_modificarProductoLayout = new javax.swing.GroupLayout(panel_modificarProducto);
        panel_modificarProducto.setLayout(panel_modificarProductoLayout);
        panel_modificarProductoLayout.setHorizontalGroup(
            panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modificarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_modificarProductoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_modificarProductoLayout.createSequentialGroup()
                        .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_actualizarProducto)
                            .addGroup(panel_modificarProductoLayout.createSequentialGroup()
                                .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textField_productoPrecioVentaModificar)
                                    .addComponent(textField_productoCostoEmpresaModificar)
                                    .addComponent(textField_productoFechaModificar)
                                    .addComponent(textField_productoCantidadModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_modificarProductoLayout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField_productoIdProductoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textField_productoNombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_productoTipoProductoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_productoTamañoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_productoAlmacenModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90))))
        );
        panel_modificarProductoLayout.setVerticalGroup(
            panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modificarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(textField_productoIdProductoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_productoNombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_productoTipoProductoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_productoTamañoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_productoAlmacenModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textField_productoPrecioVentaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textField_productoCostoEmpresaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textField_productoFechaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textField_productoCantidadModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_actualizarProducto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Modificar Venta");

        jLabel13.setText("ID del cliente");

        jLabel14.setText("ID del producto");

        jLabel15.setText("Cantidad vendida");

        jLabel16.setText("Monto pagado");

        jLabel17.setText("Fecha");

        textField_VentaCantidadModificar.setText("Ejemplo: \"1\"");

        textField_VentaIdProductoModificar.setText("Ejemplo: \"9\"");

        textField_VentaIdClienteModificar.setText("Ejemplo: \"5\"");

        textField_VentaMontoModificar.setText("Ejemplo: \"1200\"");

        textField_VentaFechaModificar.setText("Ejemplo: \"2024-11-05\"");

        btn_actualizarVenta.setText("Actualizar");
        btn_actualizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarVentaActionPerformed(evt);
            }
        });

        jLabel29.setText("ID Venta");

        textField_ventaIdVentaModificar.setText("Ejemplo: \"2\"");

        javax.swing.GroupLayout panel_modificarVentaLayout = new javax.swing.GroupLayout(panel_modificarVenta);
        panel_modificarVenta.setLayout(panel_modificarVentaLayout);
        panel_modificarVentaLayout.setHorizontalGroup(
            panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modificarVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panel_modificarVentaLayout.createSequentialGroup()
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField_ventaIdVentaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_actualizarVenta)
                            .addGroup(panel_modificarVentaLayout.createSequentialGroup()
                                .addGroup(panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textField_VentaIdClienteModificar)
                                    .addComponent(textField_VentaIdProductoModificar)
                                    .addComponent(textField_VentaCantidadModificar)
                                    .addComponent(textField_VentaMontoModificar)
                                    .addComponent(textField_VentaFechaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_modificarVentaLayout.setVerticalGroup(
            panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modificarVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(textField_ventaIdVentaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(textField_VentaIdClienteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(textField_VentaIdProductoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(textField_VentaCantidadModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(textField_VentaMontoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(textField_VentaFechaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_actualizarVenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Modificar Cliente");

        jLabel19.setText("Nombre(s)");

        jLabel20.setText("Primer apellido");

        jLabel21.setText("Segundo apellido");

        jLabel22.setText("Deuda pendiente");

        jLabel23.setText("Crédito disponible");

        jLabel24.setText("Calle");

        jLabel25.setText("Numero de casa");

        jLabel26.setText("Colonia");

        jLabel27.setText("Telefono");

        textField_clienteCreditoModificar.setText("Ejemplo: \"1000\"");

        textField_clienteDeudaModificar.setText("Ejemplo: \"5000\"");

        textField_clienteSegundoApellidoModificar.setText("Ejemplo: \"Moreno\"");

        textField_clientePrimerApellidoModificar.setText("Ejemplo: \"Alcantara\"");

        textField_clienteNombreModificar.setText("Ejemplo: \"Pedro Jesus\"");

        textField_clienteCalleModificar.setText("Ejemplo: \"Bernardo Reyes\"");

        textField_clienteNumCasaModificar.setText("104");

        textField_clienteColoniaModificar.setText("Ejemplo: \"Lopez portillo\"");

        textField_clienteTelefonoModificar.setText("Ejemplo: \"+526621006914\"");

        btn_actualizarCliente.setText("Actualizar");
        btn_actualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarClienteActionPerformed(evt);
            }
        });

        jLabel30.setText("ID Cliente");

        textField_clienteIdClienteModificar.setText("Ejemplo: \"Pedro Jesus\"");

        javax.swing.GroupLayout panel_modificarClienteLayout = new javax.swing.GroupLayout(panel_modificarCliente);
        panel_modificarCliente.setLayout(panel_modificarClienteLayout);
        panel_modificarClienteLayout.setHorizontalGroup(
            panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modificarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panel_modificarClienteLayout.createSequentialGroup()
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField_clienteIdClienteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_actualizarCliente)
                            .addGroup(panel_modificarClienteLayout.createSequentialGroup()
                                .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textField_clienteNombreModificar)
                                    .addComponent(textField_clientePrimerApellidoModificar)
                                    .addComponent(textField_clienteSegundoApellidoModificar)
                                    .addComponent(textField_clienteDeudaModificar)
                                    .addComponent(textField_clienteCreditoModificar)
                                    .addComponent(textField_clienteCalleModificar)
                                    .addComponent(textField_clienteNumCasaModificar)
                                    .addComponent(textField_clienteColoniaModificar)
                                    .addComponent(textField_clienteTelefonoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_modificarClienteLayout.setVerticalGroup(
            panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modificarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(textField_clienteIdClienteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(textField_clienteNombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(textField_clientePrimerApellidoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(textField_clienteSegundoApellidoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(textField_clienteDeudaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(textField_clienteCreditoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(textField_clienteCalleModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(textField_clienteNumCasaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(textField_clienteColoniaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_modificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(textField_clienteTelefonoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_actualizarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Ayuda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbox_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_filtro_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbox_tablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_mostrar_todo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_modificarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_modificarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_modificarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mostrar_todo)
                    .addComponent(cbox_tablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbox_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mostrar)
                    .addComponent(textField_filtro_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(panel_modificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(panel_modificarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel_modificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(100, Short.MAX_VALUE))))))
        );

        btn_consultar.setText("Consultar");
        btn_consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultarMouseClicked(evt);
            }
        });

        btn_agregar.setText("Agregar");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });

        btn_modificar.setText("Modificar");

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btn_consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mostrar_todoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrar_todoMouseClicked
        mostrarContenido(this.cbox_tablas.getSelectedItem().toString());
    }//GEN-LAST:event_btn_mostrar_todoMouseClicked

    private void btn_mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrarMouseClicked
        consultaFiltro(this.cbox_campo.getSelectedItem().toString());
    }//GEN-LAST:event_btn_mostrarMouseClicked

    private void cbox_tablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_tablasActionPerformed
        comboOpciones(this.cbox_tablas.getSelectedItem().toString());
        mostrarContenido(this.cbox_tablas.getSelectedItem().toString());
    }//GEN-LAST:event_cbox_tablasActionPerformed

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        modificar.setNewContent(new Agregar(modificar, con));
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void btn_consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarMouseClicked
        modificar.setNewContent(new Consultar(modificar, con));
    }//GEN-LAST:event_btn_consultarMouseClicked

    private void btn_actualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarProductoActionPerformed
        try {
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date fecha = formato.parse(this.textField_productoFechaModificar.getText());
            java.sql.Date fechaSql = new java.sql.Date(fecha.getTime());

            Producto p = new Producto();
            p.setId_producto(Integer.parseInt(this.textField_productoIdProductoModificar.getText()));
            p.setId_almacen(convertirAlmacen(this.combo_productoAlmacenModificar.getSelectedItem().toString()));
            p.setNombre(this.textField_productoNombreModificar.getText());
            p.setId_tamanio(convertirTamaño(this.combo_productoTamañoModificar.getSelectedItem().toString()));
            p.setPrecio_venta(Float.parseFloat(this.textField_productoPrecioVentaModificar.getText()));
            p.setCosto_empresa(Float.parseFloat(this.textField_productoCostoEmpresaModificar.getText()));
            p.setFecha_llegada(fechaSql);
            p.setCantidad_inventario(Integer.parseInt(this.textField_productoCantidadModificar.getText()));
            p.setTipo_producto(convertirTipoProducto(this.combo_productoTipoProductoModificar.getSelectedItem().toString()));
            
            ProductoDAO.Modificar(p);
            mostrarContenido(this.cbox_tablas.getSelectedItem().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btn_actualizarProductoActionPerformed

    private void tabla_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_modificarMouseClicked
        try{
            tomarDatosTabla(this.cbox_tablas.getSelectedItem().toString());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_tabla_modificarMouseClicked

    private void btn_actualizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarVentaActionPerformed
        try{
            Venta v = new Venta();
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date fecha = formato.parse(this.textField_VentaFechaModificar.getText());
            java.sql.Date fechaSql = new java.sql.Date(fecha.getTime());
            
            v.setId_venta(Integer.parseInt(this.textField_ventaIdVentaModificar.getText()));
            v.setId_cliente(Integer.parseInt(this.textField_VentaIdClienteModificar.getText()));
            v.setId_producto(Integer.parseInt(this.textField_VentaIdProductoModificar.getText()));
            v.setCantidad(Integer.parseInt(this.textField_VentaCantidadModificar.getText()));
            v.setPago_inicial(Float.parseFloat(this.textField_VentaMontoModificar.getText()));
            v.setFecha(fechaSql);
            
            VentaDAO.Modificar(v);
            mostrarContenido(this.cbox_tablas.getSelectedItem().toString());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btn_actualizarVentaActionPerformed

    private void btn_actualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarClienteActionPerformed
        try{
            Cliente c = new Cliente();
            
            c.setId_cliente(Integer.parseInt(this.textField_clienteIdClienteModificar.getText()));
            c.setNombre(this.textField_clienteNombreModificar.getText());
            c.setApellido1(this.textField_clientePrimerApellidoModificar.getText());
            c.setApellido2(this.textField_clienteSegundoApellidoModificar.getText());
            c.setDeuda_pendiente(Float.parseFloat(this.textField_clienteDeudaModificar.getText()));
            c.setCredito_disponible(Float.parseFloat(this.textField_clienteCreditoModificar.getText()));
            c.setCalle(this.textField_clienteCalleModificar.getText());
            c.setNumero_casa(this.textField_clienteNumCasaModificar.getText());
            c.setColonia(this.textField_clienteColoniaModificar.getText());
            c.setTelefono(this.textField_clienteTelefonoModificar.getText());
            
            ClienteDAO.Modificar(c);
            mostrarContenido(this.cbox_tablas.getSelectedItem().toString());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btn_actualizarClienteActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        con.cerrarConexion();
        modificar.setContentPane(new Login(modificar));
        modificar.revalidate();
        modificar.repaint();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        modificar.setContentPane(new Eliminar(modificar, con));
        modificar.revalidate();
        modificar.repaint();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void mostrarContenido(String tabla){
        switch (tabla) {
            case "Productos":
                ProductoDAO.consultarTodov2(tabla_modificar);
                break;

            case "Ventas":
                VentaDAO.consultarTodov2(tabla_modificar);
                break;

            case "Clientes":
                ClienteDAO.ConsultarTodo(tabla_modificar);
                break;
        }
    }
    
    private void consultaFiltro(String filtro) {
        if (this.cbox_tablas.getSelectedItem().toString().equals("Productos")) {
            switch (filtro) {
                case "ID Producto":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "id_producto", this.textField_filtro_buscar.getText());
                    break;

                case "ID Almacen":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "id_almacen", this.textField_filtro_buscar.getText());
                    break;

                case "Nombre":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "nombre", this.textField_filtro_buscar.getText());
                    break;

                case "Tamaño":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "id_tamano", this.textField_filtro_buscar.getText());
                    break;

                case "Precio":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "precio_venta", this.textField_filtro_buscar.getText());
                    break;

                case "Costo":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "costo_empresa", this.textField_filtro_buscar.getText());
                    break;

                case "Fecha":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "fecha_llegada", this.textField_filtro_buscar.getText());
                    break;

                case "Stock":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "cantidad_inventario", this.textField_filtro_buscar.getText());
                    break;

                case "Tipo producto":
                    ProductoDAO.consultaFiltro(this.tabla_modificar, "id_tipo_producto", this.textField_filtro_buscar.getText());
                    break;
            }
        }

        if (this.cbox_tablas.getSelectedItem().toString().equals("Ventas")) {
            switch (filtro) {
                case "ID Venta":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "v", "id_venta", this.textField_filtro_buscar.getText());
                    break;

                case "ID Cliente":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "v", "id_cliente", this.textField_filtro_buscar.getText());
                    break;

                case "Nombre Cliente":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "c", "nombre", this.textField_filtro_buscar.getText());
                    break;

                case "Domicilio":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "c", "domicilio", this.textField_filtro_buscar.getText());
                    break;

                case "Telefono":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "c", "telefono", this.textField_filtro_buscar.getText());
                    break;

                case "Producto Vendido":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "p", "nombre", this.textField_filtro_buscar.getText());
                    break;

                case "Tipo Producto":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "p", "id_tipo_producto", this.textField_filtro_buscar.getText());
                    break;

                case "Precio":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "p", "precio_venta", this.textField_filtro_buscar.getText());
                    break;

                case "Monto Pagado":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "v", "pago_inicial", this.textField_filtro_buscar.getText());
                    break;

                case "Deuda Pendiente":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "v", "deuda_pendiente", this.textField_filtro_buscar.getText());
                    break;

                case "Fecha de Venta":
                    VentaDAO.consultarFiltro(this.tabla_modificar, "v", "fecha", this.textField_filtro_buscar.getText());
                    break;
            }
        }

        if (this.cbox_tablas.getSelectedItem().toString().equals("Clientes")) {
            switch (filtro) {
                case "ID cliente":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "id_cliente", this.textField_filtro_buscar.getText());
                    break;

                case "Nombre":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "nombre", this.textField_filtro_buscar.getText());
                    break;

                case "Primer apellido":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "apellido1", this.textField_filtro_buscar.getText());
                    break;

                case "Segundo apellido":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "apellido2", this.textField_filtro_buscar.getText());
                    break;

                case "Deuda pendiente":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "deuda_pendiente", this.textField_filtro_buscar.getText());
                    break;

                case "Crédito disponible":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "credito_disponible", this.textField_filtro_buscar.getText());
                    break;

                case "Calle":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "calle", this.textField_filtro_buscar.getText());
                    break;

                case "Número casa":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "numero_casa", this.textField_filtro_buscar.getText());
                    break;

                case "Colonia":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "colonia", this.textField_filtro_buscar.getText());
                    break;

                case "Telefono":
                    ClienteDAO.ConsultarFiltroV2(tabla_modificar, "telefono", this.textField_filtro_buscar.getText());
                    break;
            }
        }
    }

    private void comboOpciones(String seleccion) {
        if (seleccion == "Productos") {
            this.cbox_campo.removeAllItems();
            this.cbox_campo.addItem("ID Producto");
            this.cbox_campo.addItem("ID Almacen");
            this.cbox_campo.addItem("Nombre");
            this.cbox_campo.addItem("Tamaño");
            this.cbox_campo.addItem("Precio");
            this.cbox_campo.addItem("Costo");
            this.cbox_campo.addItem("Fecha");
            this.cbox_campo.addItem("Stock");

            this.panel_modificarProducto.setVisible(true);
            this.panel_modificarProducto.setEnabled(true);
            this.panel_modificarVenta.setVisible(false);
            this.panel_modificarVenta.setEnabled(false);
            this.panel_modificarCliente.setVisible(false);
            this.panel_modificarCliente.setEnabled(false);
        }
        if (seleccion == "Ventas") {
            this.cbox_campo.removeAllItems();
            this.cbox_campo.addItem("ID Venta");
            this.cbox_campo.addItem("ID Cliente");
            this.cbox_campo.addItem("Nombre Cliente");
            this.cbox_campo.addItem("Domicilio");
            this.cbox_campo.addItem("Telefono");
            this.cbox_campo.addItem("Producto Vendido");
            this.cbox_campo.addItem("Tipo Producto");
            this.cbox_campo.addItem("Precio");
            this.cbox_campo.addItem("Monto Pagado");
            this.cbox_campo.addItem("Deuda Pendiente");
            this.cbox_campo.addItem("Fecha de Venta");

            this.panel_modificarProducto.setVisible(false);
            this.panel_modificarProducto.setEnabled(false);
            this.panel_modificarVenta.setVisible(true);
            this.panel_modificarVenta.setEnabled(true);
            this.panel_modificarCliente.setVisible(false);
            this.panel_modificarCliente.setEnabled(false);
        }
        if (seleccion == "Clientes") {
            this.cbox_campo.removeAllItems();
            this.cbox_campo.addItem("ID cliente");
            this.cbox_campo.addItem("Nombre");
            this.cbox_campo.addItem("Primer apellido");
            this.cbox_campo.addItem("Segundo apellido");
            this.cbox_campo.addItem("Deuda pendiente");
            this.cbox_campo.addItem("Crédito disponible");
            this.cbox_campo.addItem("Calle");
            this.cbox_campo.addItem("Número casa");
            this.cbox_campo.addItem("Colonia");
            this.cbox_campo.addItem("Telefono");

            this.panel_modificarProducto.setVisible(false);
            this.panel_modificarProducto.setEnabled(false);
            this.panel_modificarVenta.setVisible(false);
            this.panel_modificarVenta.setEnabled(false);
            this.panel_modificarCliente.setVisible(true);
            this.panel_modificarCliente.setEnabled(true);
        }
    }

    private int convertirAlmacen(String almacen) {
        switch (almacen) {
            case "ALFA":
                return 1;

            case "BETA":
                return 1;
        }

        return -1;
    }

    private int convertirTamaño(String tamanio) {
        switch (tamanio) {
            case "Chico":
                return 1;

            case "Mediano":
                return 2;

            case "Grande":
                return 3;

            case "Muy grande":
                return 4;
        }

        return -1;
    }

    private int convertirTipoProducto(String tipo) {
        switch (tipo) {
            case "Muebles":
                return 1;

            case "Electrodomésticos":
                return 2;
        }

        return -1;
    }

    private void tomarDatosTabla(String tabla){
        int row = this.tabla_modificar.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) this.tabla_modificar.getModel();

        switch (tabla) {
            case "Productos":
                row = this.tabla_modificar.getSelectedRow();
                model =(DefaultTableModel) this.tabla_modificar.getModel(); 
                
                this.textField_productoIdProductoModificar.setText(model.getValueAt(row, 0).toString());
                this.textField_productoNombreModificar.setText(model.getValueAt(row, 1).toString());
                
                
                switch (model.getValueAt(row, 2).toString()) {
                    case "Muebles":
                        this.combo_productoTipoProductoModificar.setSelectedIndex(0);
                        break;

                    case "Electrodomésticos":
                        this.combo_productoTipoProductoModificar.setSelectedIndex(1);
                        break;
                }
                
                switch (model.getValueAt(row, 3).toString()) {
                    case "chico":
                        this.combo_productoTamañoModificar.setSelectedIndex(0);
                        break;

                    case "mediano":
                        this.combo_productoTamañoModificar.setSelectedIndex(1);
                        break;

                    case "grande":
                        this.combo_productoTamañoModificar.setSelectedIndex(2);
                        break;

                    case "muy grande":
                        this.combo_productoTamañoModificar.setSelectedIndex(3);
                        break;
                }
                
                switch (model.getValueAt(row, 4).toString()) {
                    case "ALFA":
                        this.combo_productoAlmacenModificar.setSelectedIndex(0);
                        break;

                    case "BETA":
                        this.combo_productoAlmacenModificar.setSelectedIndex(1);
                        break;
                }

                this.textField_productoPrecioVentaModificar.setText(model.getValueAt(row, 5).toString());
                this.textField_productoCostoEmpresaModificar.setText(model.getValueAt(row, 6).toString());
                this.textField_productoFechaModificar.setText(model.getValueAt(row, 7).toString());
                this.textField_productoCantidadModificar.setText(model.getValueAt(row, 8).toString());
                
                break;

            case "Ventas":
                row = this.tabla_modificar.getSelectedRow();
                model =(DefaultTableModel) this.tabla_modificar.getModel(); 
                
                this.textField_ventaIdVentaModificar.setText(model.getValueAt(row, 0).toString());
                this.textField_VentaIdClienteModificar.setText(model.getValueAt(row, 1).toString());
                this.textField_VentaCantidadModificar.setText(model.getValueAt(row, 7).toString());
                this.textField_VentaMontoModificar.setText(model.getValueAt(row, 9).toString());
                this.textField_VentaFechaModificar.setText(model.getValueAt(row, 11).toString());
                break;

            case "Clientes":
                row = this.tabla_modificar.getSelectedRow();
                model =(DefaultTableModel) this.tabla_modificar.getModel(); 
                
                this.textField_clienteIdClienteModificar.setText(model.getValueAt(row, 0).toString());
                this.textField_clienteNombreModificar.setText(model.getValueAt(row, 1).toString());
                this.textField_clientePrimerApellidoModificar.setText(model.getValueAt(row, 2).toString());
                this.textField_clienteSegundoApellidoModificar.setText(model.getValueAt(row, 3).toString());
                this.textField_clienteDeudaModificar.setText(model.getValueAt(row, 4).toString());
                this.textField_clienteCreditoModificar.setText(model.getValueAt(row, 5).toString());
                this.textField_clienteCalleModificar.setText(model.getValueAt(row, 6).toString());
                this.textField_clienteNumCasaModificar.setText(model.getValueAt(row, 7).toString());
                this.textField_clienteColoniaModificar.setText(model.getValueAt(row, 8).toString());
                this.textField_clienteTelefonoModificar.setText(model.getValueAt(row, 9).toString());
                
                break;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarCliente;
    private javax.swing.JButton btn_actualizarProducto;
    private javax.swing.JButton btn_actualizarVenta;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_mostrar;
    public javax.swing.JButton btn_mostrar_todo;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cbox_campo;
    private javax.swing.JComboBox<String> cbox_tablas;
    private javax.swing.JComboBox<String> combo_productoAlmacenModificar;
    private javax.swing.JComboBox<String> combo_productoTamañoModificar;
    private javax.swing.JComboBox<String> combo_productoTipoProductoModificar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_modificarCliente;
    private javax.swing.JPanel panel_modificarProducto;
    private javax.swing.JPanel panel_modificarVenta;
    public javax.swing.JTable tabla_modificar;
    private javax.swing.JTextField textField_VentaCantidadModificar;
    private javax.swing.JTextField textField_VentaFechaModificar;
    private javax.swing.JTextField textField_VentaIdClienteModificar;
    private javax.swing.JTextField textField_VentaIdProductoModificar;
    private javax.swing.JTextField textField_VentaMontoModificar;
    private javax.swing.JTextField textField_clienteCalleModificar;
    private javax.swing.JTextField textField_clienteColoniaModificar;
    private javax.swing.JTextField textField_clienteCreditoModificar;
    private javax.swing.JTextField textField_clienteDeudaModificar;
    private javax.swing.JTextField textField_clienteIdClienteModificar;
    private javax.swing.JTextField textField_clienteNombreModificar;
    private javax.swing.JTextField textField_clienteNumCasaModificar;
    private javax.swing.JTextField textField_clientePrimerApellidoModificar;
    private javax.swing.JTextField textField_clienteSegundoApellidoModificar;
    private javax.swing.JTextField textField_clienteTelefonoModificar;
    private javax.swing.JTextField textField_filtro_buscar;
    private javax.swing.JTextField textField_productoCantidadModificar;
    private javax.swing.JTextField textField_productoCostoEmpresaModificar;
    private javax.swing.JTextField textField_productoFechaModificar;
    private javax.swing.JTextField textField_productoIdProductoModificar;
    private javax.swing.JTextField textField_productoNombreModificar;
    private javax.swing.JTextField textField_productoPrecioVentaModificar;
    private javax.swing.JTextField textField_ventaIdVentaModificar;
    // End of variables declaration//GEN-END:variables
}
